### ISSUE TITLE
OptiFine HD U G5 incompatibility in 1.12.2.

### ISSUE THREAD

**Issue by DesolateIntention** [layou233/smooth-sneaking-mod#1]
The game crashes on startup if OptiFine HD U G5 and the mod are present.

- Windows 11.
- Forge 1.12.2 14.23.5.2860.

**Comment by layou233** [comment]
I can't reproduce the crash.🤔

Reminder: This mod requires mixin. Did you install the [MixinBooter mod](https://modrinth.com/mod/mixinbooter) on 1.12.2?

If you still have the problem please post your crash report and it may help.

**Comment by DesolateIntention** [comment]
You're right. I hadn't installed it. It works fine now. Thanks!
